- name: Login to rancher
  uri:
    url: '{{ rancher_url }}/v3-public/localProviders/local?action=login'
    method: POST
    body: {"username": "admin", "password": "{{ rancher_admin_password }}"}
    status_code: 201
    body_format: json
    validate_certs: False
  register: login_result
  until: login_result.status == 201

- name: Create api key (expires in 1 day)
  uri:
    url: '{{ rancher_url }}/v3/token'
    method: POST
    body: {"current":false, "expired":false, "isDerived":false, "ttl":86400000, "type":"token", "description":"certamanger-catalog"}
    status_code: 201
    body_format: json
    headers:
      Authorization: "Bearer {{ login_result.json.token }}"
    validate_certs: False
  register: api_key_result

- name: Get cluster
  uri:
    url: '{{ rancher_url }}/v3/clusters?name={{ rancher_cluster_name }}'
    method: GET
    status_code: 200
    body_format: json
    headers:
      Authorization: "Bearer {{ api_key_result.json.token }}"
    validate_certs: False
  register: cluster_result


- name: Get project associated to cluster
  uri:
    url: '{{ rancher_url }}/v3/projects?clusterId={{ cluster_result.json.data[0].id }}'
    method: GET
    status_code: 200
    body_format: json
    headers:
      Authorization: "Bearer {{ api_key_result.json.token }}"
    validate_certs: False
  register: project_result

- name: Create namespace cert-manager
  uri:
    url: '{{ rancher_url }}/v3/clusters/{{ cluster_result.json.data[0].id }}/namespace'
    method: POST
    body: {"type":"namespace","name":"cert-manager","projectId":"{{ project_result.json.data[1].id }}"}
    status_code: 201
    body_format: json
    headers:
      Authorization: "Bearer {{ api_key_result.json.token }}"
    validate_certs: False

- name: Install catalog
  uri:
    url: '{{ rancher_url }}/v3/projects/{{ project_result.json.data[1].id }}/app'
    method: POST
    body: {"prune":false,"type":"app","name":"cert-manager","answers":{"defaultImage":"true","image.repository":"quay.io/jetstack/cert-manager-controller","image.tag":"v0.5.2","webhook.image.repository":"quay.io/jetstack/cert-manager-webhook","webhook.image.tag":"v0.5.2","replicaCount":"1","clusterissuerEnabled":"true","ingressShim.defaultIssuerName":"letsencrypt-staging","{{ cluster_issuer_name }}":"{{ letsencrypt_email }}","createCustomResource":"true","webhook.enabled":"false","webhook.replicaCount":"1","webhook.extraArgs":"[]"},"targetNamespace":"cert-manager","externalId":"catalog://?catalog=library&template=cert-manager&version=v0.5.2","projectId":"{{ project_result.json.data[1].id }}"}
    status_code: 201
    body_format: json
    headers:
      Authorization: "Bearer {{ api_key_result.json.token }}"
    validate_certs: False
